#cloud-config

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
autoinstall:

  apt:
    geoip: true

  ssh:
    allow-pw: true
    install-server: true

  keyboard:
    layout: us
    toggle: null
    variant: ''

  late-commands:
    - "mkdir /mnt/cidata"
    - "mount -o ro -t auto /dev/disk/by-label/cidata /mnt/cidata"
    - "curtin in-target -- mkdir -p /var/lib/viai"
    - "cp --force --recursive --verbose /mnt/cidata/. /target/var/lib/viai/"

  storage:
    layout:
      name: lvm

  user-data:
    apt:
      sources:
        google_cloud_sdk:
          filename: "google-cloud-sdk.list"
          source: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"

    bootcmd:
      - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

    # Explicitly set the passwords for the following users, and expire those passwords
    chpasswd:
      expire: true
      list:
        - viai-admin:viai-admin
        - ubuntu:ubuntu

    groups:
      - microk8s

    growpart:
      mode: auto
      devices: ["/"]
      ignore_growroot_disabled: false

    hostname: viai-nexcom

    locale: "en_US.UTF-8"

    # update the contents of /etc/hosts based on the hostname/fqdn specified
    manage_etc_hosts: true

    # Set up the NTP client with default configuration and client
    ntp:
      enabled: true
      ntp_client: auto

    package_update: true
    package_upgrade: true
    package_reboot_if_required: true

    packages:
      - alsa-utils
      - ubuntu-drivers-common

    power_state:
      mode: reboot
      message: "Rebooting the system..."

    random_seed:
      file: /dev/urandom
      command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
      command_required: true

    resize_rootfs: true

    # We don't use a script because Ubuntu autoinstall doesn't support generating
    # a user-data file that includes scripts that are not in autoinstall.user-data
    runcmd:
      - bash /var/lib/viai/edge-server/node-setup.sh
      - bash /var/lib/viai/scripts/0-setup-machine.sh
      - bash /var/lib/viai/scripts/1-deploy-app.sh

    # Allow SSH password authentication for the first login
    ssh_pwauth: true

    # Remove default host keys if any
    ssh_deletekeys: true

    timezone: "Etc/UTC"

    users:
      - default
      - name: viai-admin
        groups: adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video
        # Don't lock the user to allow the first login with a password,
        # so that we initialize key-based authentication later.
        lock_passwd: false
        shell: /usr/bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL

    write_files:
      - path: /etc/sysctl.d/enable-ip-forwarding.conf
        content: |
          net.ipv4.conf.all.forwarding=1
  version: 1
...
