title: Visual Inspection AI Edge
description: Deploy and serve Visual Inspection AI models on an edge server.
theme: just-the-docs

url: https://GoogleCloudPlatform.github.io/solutions-viai-edge-provisioning-configuration
baseurl: /docs

aux_links:
  Template Repository: https://github.com/GoogleCloudPlatform/solutions-viai-edge-provisioning-configuration
