---
name: Build and push container images

env:
  CONTAINER_IMAGE_REGISTRY: ghcr.io

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/build-container-images.yml"
      - ".github/workflows/lint.yml"
      - "docker/**"
  pull_request:
    paths:
      - ".github/workflows/build-container-images.yml"
      - ".github/workflows/lint.yml"
      - "docker/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build-container-images:
    env:
      CONTAINER_IMAGE_ID: "${{ github.repository }}-${{ matrix.container-image-context-directory }}"
    needs:
      - lint
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the container image registry
        uses: docker/login-action@v3.0.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.CONTAINER_IMAGE_REGISTRY }}
          username: ${{ github.actor }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            ${{ env.CONTAINER_IMAGE_REGISTRY }}/${{ env.CONTAINER_IMAGE_ID }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build the ${{ matrix.container-image-context-directory }} container image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: docker/${{ matrix.container-image-context-directory }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        container-image-context-directory:
          - copy-images
          - os-image-builder
          - private-repo
          - terraform
...
