---
name: Build and push container images

env:
  CONTAINER_IMAGE_REGISTRY: ghcr.io

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  build-container-images:
    env:
      CONTAINER_IMAGE_ID: "${{ github.repository }}-${{ matrix.container-images.name }}"
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.3.0
        with:
          images: |
            ${{ env.CONTAINER_IMAGE_REGISTRY }}/${{ env.CONTAINER_IMAGE_ID }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build the ${{ matrix.container-images.name }} container image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.container-images.context-directory }}
          file: ${{ matrix.container-images.file }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        container-images:
          - name: copy-images
            context-directory: docker/copy-images
            file: docker/copy-images/Dockerfile
          - name: os-image-builder
            context-directory: docker/os-image-builder
            file: docker/os-image-builder/Dockerfile
          - name: private-repo
            context-directory: docker/private-repo
            file: docker/private-repo/Dockerfile
          - name: terraform
            context-directory: docker/terraform
            file: docker/terraform/Dockerfile
          - name: yq
            context-directory: docker/yq
            file: docker/yq/Dockerfile
          - name: jekyll-documentation
            context-directory: docs
            file: docker/documentation-site-builder/Dockerfile
  build-container-images-script:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container images from script
        run: |
          tests/build-container-images.sh
...
