---
name: Check PR origin for users with push access to the repository
on: [pull_request]
jobs:
  check-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR comes from a fork
        uses: actions/github-script@v7
        id: check-origin
        with:
          script: |
            const repoName = context.payload.repository.full_name;
            console.log(`Repository full name: ${repoName}`);

            const pr = context.payload.pull_request;
            const prRepoName = pr.head.repo.full_name;
            console.log(`PR head repository full name: ${prRepoName}`);
            const isFork = (prRepoName !== repoName);
            core.setOutput('isFork', isFork);

      - name: Get user permissions
        uses: actions/github-script@v7
        id: get-permissions
        with:
          script: |
            const username = context.payload.pull_request.user.login;
            const permissions = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: username
            });
            const hasPushAccess = permissions.data.permission == 'admin'
              || permissions.data.permission == 'write';
            core.setOutput('hasPushAccess', hasPushAccess);

      - name: Fail if PR is from a fork and user has push access
        if: >
          steps.check-origin.outputs.isFork == 'true'
          && steps.get-permissions.outputs.hasPushAccess == 'true'
        run: |
          echo "This pull request is from a forked repository. We only accept PRs from branches within the repository for users with push access."
          exit 1
...
