---
name: Check PR origin for users with push access to the repository
on: [pull_request]
jobs:
  check-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR information
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const baseRef = pr.base.ref;
            const repoName = pr.base.repo.full_name;
            const isFork = (repoName !== context.repo.owner + '/' + context.repo.name);
            core.setOutput('isFork', isFork);

      - name: Get user permissions
        uses: actions/github-script@v6
        id: get-permissions
        with:
          script: |
            const username = context.payload.pull_request.user.login;
            const permissions = await github.repos.get({
              owner: context.repo.owner,
              repo: context.repo.name,
              username: username
            });
            const hasPushAccess = permissions.data.permissions.push;
            core.setOutput('hasPushAccess', hasPushAccess);

      - name: Fail if PR is from a fork and user has push access
        if: >
          steps.check_origin.outputs.isFork
          && steps.get-permissions.outputs.hasPushAccess
        run: |
          echo "This pull request is from a forked repository. We only accept PRs from branches within the repository for users with push access."
          exit 1
...
