---
name: Validate Terraform

# Controls when the workflow will run
on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Validate Terraform descriptors using the validation script
        run: |
          tests/validate-terraform.sh
...
