---
name: Validate Terraform

# Controls when the workflow will run
on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        # Do not initialize backend
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate
...
