---
name: Validate shell scripts

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - "scripts/**"

  pull_request:
    paths:
      - "scripts/**"

  # Validate scrtips every Sunday at 00:00
  schedule:
    - cron:  '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  validate-shell-scripts-macos:
    strategy:
      matrix:
        os: [macos-latest]
    needs:
      - lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Test common functions and variables"
        run: |
          set -o errexit
          set -o nounset

          brew install docker
          colima start

          ./tests/test-common.sh
      # https://github.com/orgs/community/discussions/25777#discussioncomment-3249229
      # We need to manually install docker to verify scripts
      - name: "Generate Edge server configuration assets and ISO file"
        run: |
          set -o errexit
          set -o nounset

          ./tests/test-shell-scripts.sh
      - name: "Verrify Anthos Version is configured in common.sh"
        run: |
          set -o errexit
          set -o nounset

          ./tests/test-anthos-version.sh
  validate-shell-scripts-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    needs:
      - lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: "Test common functions and variables"
        run: |
          set -o errexit
          set -o nounset

          ./tests/test-common.sh
      - name: "Generate Edge server configuration assets and ISO file"
        run: |
          set -o errexit
          set -o nounset

          ./tests/test-shell-scripts.sh
      - name: "Verrify Anthos Version is configured in common.sh"
        run: |
          set -o errexit
          set -o nounset

          ./tests/test-anthos-version.sh
...
